apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: hudakmshs/ambulance-ufe-mhx
    newName: hudakmshs/ambulance-ufe-mhx # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
    newTag: main.20260214.1841 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
